server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Redireciona todas as rotas para o index.html (necessário para o Angular Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy reverso para o backend — evita CORS em produção
    location /api/ {
        proxy_pass http://pgdi-backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}